# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vmt < Formula
  desc "Voice Memos transcription CLI"
  homepage "https://github.com/matsubo/voice-memo-stt"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/matsubo/voice-memo-stt/releases/download/v0.2.0/voice-memo-stt_darwin_amd64.tar.gz"
    sha256 "dd444b4d5fc769a4a698d031e77f035e15c423da12c1a88c4d02a803d1269818"

    define_method(:install) do
      bin.install "vmt"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/matsubo/voice-memo-stt/releases/download/v0.2.0/voice-memo-stt_darwin_arm64.tar.gz"
    sha256 "02740cf3503b8e1a74324b7c29d9f145cf4012ddf7c33f508cf09ab7e13c95a2"

    define_method(:install) do
      bin.install "vmt"
    end
  end
end
