# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vmt < Formula
  desc "Voice Memos transcription CLI"
  homepage "https://github.com/matsubo/voice-memo-stt"
  version "0.3.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/matsubo/voice-memo-stt/releases/download/v0.3.0/voice-memo-stt_darwin_amd64.tar.gz"
    sha256 "ef318fc3d522c247b6950b4235076209ef608d94c6c4a95f022a880e587aca5f"

    define_method(:install) do
      bin.install "vmt"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/matsubo/voice-memo-stt/releases/download/v0.3.0/voice-memo-stt_darwin_arm64.tar.gz"
    sha256 "a7428de07e817fd06dced7039ce07978eb5cb253f3388f3e7244c96c6feeb3ed"

    define_method(:install) do
      bin.install "vmt"
    end
  end
end
